Repository redis/redis-om-dotnet, pull requests merged in 2022-10, with the labels that each got.

#210 fixing other stateful queries issue
  src/Redis.OM/Aggregation/RedisAggregationSet.cs
  src/Redis.OM/Searching/RedisCollection.cs
  src/Redis.OM/Searching/RedisQueryProvider.cs
Labels: bugfix

#226 Adding Delete Document Stored Example
  examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument.sln
  examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Customer.cs
  examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Person.cs
  examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Program.cs
  examples/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument/Redis.OM.DeleteDocument.csproj
Labels: hacktoberfest

#228 Add Basic Matching Queries Example
  examples/Redis.OM.BasicMatchingQueries/Helpers/RedisHelper.cs
  examples/Redis.OM.BasicMatchingQueries/Models/Address.cs
  examples/Redis.OM.BasicMatchingQueries/Models/Customer.cs
  examples/Redis.OM.BasicMatchingQueries/Models/CustomerRelation.cs
  examples/Redis.OM.BasicMatchingQueries/Program.cs
  examples/Redis.OM.BasicMatchingQueries/Redis.OM.BasicMatchingQueries.csproj
Labels: hacktoberfest

#230 Full-text search within an index example (#220)
  README.md
  examples/Redis.OM.FullTextSearch/Models/Awards.cs
  examples/Redis.OM.FullTextSearch/Models/Genre.cs
  examples/Redis.OM.FullTextSearch/Models/Movie.cs
  examples/Redis.OM.FullTextSearch/Program.cs
  examples/Redis.OM.FullTextSearch/Redis.OM.FullTextSearch.csproj
  examples/Redis.OM.FullTextSearch/Redis.OM.FullTextSearch.sln
  examples/Redis.OM.FullTextSearch/RedisHelper/RedisHelper.cs
Labels: hacktoberfest

#233 fix: Prevent duplicate task keys in FindByIdsAsync
  src/Redis.OM/Searching/RedisCollection.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Labels: bugfix, hacktoberfest, hacktoberfest-accepted

#232 Create an Index and Store Documents
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.sln
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Helpers/SeedDataHelpers.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Address.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Customer.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Employee.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Models/Store.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Program.cs
  examples/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore/Redis.OM.CreateIndexStore.csproj
Labels: hacktoberfest

#231 Quering string array example added #issue 221
  examples/Redis.OM.QueryingStringsWithinArrays/Experience.cs
  examples/Redis.OM.QueryingStringsWithinArrays/Helpers.cs
  examples/Redis.OM.QueryingStringsWithinArrays/Program.cs
  examples/Redis.OM.QueryingStringsWithinArrays/Redis.OM.QueryingStringsWithinArrays.csproj
  examples/Redis.OM.QueryingStringsWithinArrays/Redis.OM.QueryingStringsWithinArrays.sln
Labels: hacktoberfest, hacktoberfest-accepted

#52 Enforced culture invariant compliance
  src/Redis.OM.Analyzer/Redis.OM.Analyzer.csproj
  src/Redis.OM/Aggregation/AggregationPredicates/AggregateSortBy.cs
  src/Redis.OM/Aggregation/AggregationPredicates/ApplyFunctions.cs
  src/Redis.OM/Common/ExpressionParserUtilities.cs
  src/Redis.OM/GeoLoc.cs
  src/Redis.OM/RedisReply.cs
  src/Redis.OM/SearchExtensions.cs
  src/Redis.OM/Searching/RedisQueryProvider.cs
  test/Redis.OM.Unit.Tests/GeoLocTests.cs
  test/Redis.OM.Unit.Tests/Helper.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/AggregationFunctionalTests.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/ApplyFunctionTests.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/ReducerTests.cs
Labels: bugfix

#234 Bugfix for GeoLoc Serialization in Different Cultures
  README.md
  src/Redis.OM/GeoLoc.cs
  src/Redis.OM/Redis.OM.csproj
  test/Redis.OM.Unit.Tests/GeoLocTests.cs
Labels: bugfix, hacktoberfest

#240 adding ability to index and query datetimes
  README.md
  src/Redis.OM/Common/ExpressionParserUtilities.cs
  src/Redis.OM/Common/ExpressionTranslator.cs
  src/Redis.OM/Modeling/DateTimeJsonConverter.cs
  src/Redis.OM/Modeling/TypeDeterminationUtilities.cs
  src/Redis.OM/Redis.OM.csproj
  test/Redis.OM.Unit.Tests/RediSearchTests/ObjectWithDateTime.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
  test/Redis.OM.Unit.Tests/RedisSetupCollection.cs
Labels: enhancement, breakingchange, feature
