Repository redis/redis-om-dotnet, pull requests merged in 2022-08, with the labels that each got.

#167 Adding FindByIdsAsync
  src/Redis.OM/Searching/IRedisCollection.cs
  src/Redis.OM/Searching/RedisCollection.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Labels: enhancement

#168 adding ability to configure stopwords on an index
  src/Redis.OM/Modeling/DocumentAttribute.cs
  src/Redis.OM/Modeling/RedisIndex.cs
  src/Redis.OM/stylecop.ruleset
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchTests.cs
  test/Redis.OM.Unit.Tests/RedisSetupCollection.cs
  test/Redis.OM.Unit.Tests/Serialization/ObjectWithTwoStopwords.cs
  test/Redis.OM.Unit.Tests/Serialization/ObjectWithZeroStopwords.cs
Labels: enhancement

#178 Add Wrapper for FT.INFO to get index information
  README.md
  src/Redis.OM/RediSearchCommands.cs
  src/Redis.OM/RedisIndexInfo.cs
  test/Redis.OM.Test.ConsoleApp/Program.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/RedisIndexTests.cs
Labels: enhancement

#177 Update Test Project to .NET 6
  docker/dotnet/dockerfile
  dockerfile
  test/Redis.OM.Test.AspDotnetCore/Redis.OM.Test.AspDotnetCore.csproj
  test/Redis.OM.Test.ConsoleApp/Redis.OM.Test.ConsoleApp.csproj
  test/Redis.OM.Unit.Tests/Redis.OM.Unit.Tests.csproj
Labels: maintenance

#166 Features/key TTL
  src/Redis.OM.POC/RedisConnection.cs
  src/Redis.OM/Contracts/IRedisConnection.cs
  src/Redis.OM/RedisCommands.cs
  src/Redis.OM/RedisConnection.cs
  src/Redis.OM/Searching/IRedisCollection.cs
  src/Redis.OM/Searching/RedisCollection.cs
  test/Redis.OM.Unit.Tests/ConnectionTests.cs
  test/Redis.OM.Unit.Tests/CoreTests.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
  test/Redis.OM.Unit.Tests/Serialization/BasicHashObject.cs
  test/Redis.OM.Unit.Tests/Serialization/BasicJsonObject.cs
  test/Redis.OM.Unit.Tests/Serialization/DateTimeSerializationTest.cs
Labels: enhancement

#185 Fix #170 to save FindById result to StateManager
  src/Redis.OM/Searching/RedisCollection.cs
  test/Redis.OM.Unit.Tests/RediSearchTests/SearchFunctionalTests.cs
Labels: bugfix

#187 Make FindByIdAsync() work asynchronous independent of the type of T in RedisCollection class.
  README.md
  src/Redis.OM/RedisCommands.cs
Labels: bugfix
